version: '3.8'

services:
  hackathon-backend:
    image: ${DOCKER_REGISTRY-}hackathon-back
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_CONTENT_DIR=.
    ports:
      - "8080:8000"